### ISSUE TITLE
Errors when running NLRtracker

### ISSUE THREAD

**Issue by soungalo** [slt666666/NLRtracker#1]
Hello,
I am trying to run NLRtracker using the following command:
`bash NLRtracker.sh -s /path/to/genome.fasta -o /path/to/NLRtracker/RESULT -t n -c 60`
I am getting several error messages and can't really say what is going wrong. Here is the stdout. Can you please help detecting the problem?

```
---------------------- input & option -----------------------
Fasta file             = /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
output directory       = /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/output/NLRtracker/RESULT
Seqtype of fasta       = n
Number of CPUs         = 60

---------------------- input & option -----------------------
NLRtracker.sh: line 44: tmp_/groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa.fasta: No such file or directory
awk: cmd. line:1: (FILENAME=- FNR=70) fatal: printf to "standard output" failed (Broken pipe)
cat: write error: Broken pipe

Run Interproscan
InterProScan version 5.32-71.0
InterProScan 64-Bit build  (requires  Java 1.8)

interproscan.sh -i /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa -f gff3 -t n -o /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/output/NLRtracker/RESULT/interpro_result.gff -cpu 60 -appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles
12/02/2021 09:57:00:576 Welcome to InterProScan-5.32-71.0
12/02/2021 09:57:06:502 Running InterProScan v5 in STANDALONE mode... on Linux
12/02/2021 09:57:17:863 Loading file /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
12/02/2021 09:57:17:902 Running the following analyses:
[CDD-3.16,Gene3D-4.2.0,Pfam-32.0,PRINTS-42.0,ProSiteProfiles-2018_02,SMART-7.1,SUPERFAMILY-1.75]
12/02/2021 09:57:38:536 Loading file /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
12/02/2021 09:57:38:545 Running the following analyses:
[CDD-3.16,Gene3D-4.2.0,Pfam-32.0,PRINTS-42.0,ProSiteProfiles-2018_02,SMART-7.1,SUPERFAMILY-1.75]
12/02/2021 09:57:59:813 Loading file /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
12/02/2021 09:57:59:820 Running the following analyses:
[CDD-3.16,Gene3D-4.2.0,Pfam-32.0,PRINTS-42.0,ProSiteProfiles-2018_02,SMART-7.1,SUPERFAMILY-1.75]
12/02/2021 09:58:22:200 Loading file /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
12/02/2021 09:58:22:203 Running the following analyses:
[CDD-3.16,Gene3D-4.2.0,Pfam-32.0,PRINTS-42.0,ProSiteProfiles-2018_02,SMART-7.1,SUPERFAMILY-1.75]
12/02/2021 09:58:44:687 Loading file /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
12/02/2021 09:58:44:895 Running the following analyses:
[CDD-3.16,Gene3D-4.2.0,Pfam-32.0,PRINTS-42.0,ProSiteProfiles-2018_02,SMART-7.1,SUPERFAMILY-1.75]
12/02/2021 09:59:02:563 Loading file /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
12/02/2021 09:59:02:567 Running the following analyses:
[CDD-3.16,Gene3D-4.2.0,Pfam-32.0,PRINTS-42.0,ProSiteProfiles-2018_02,SMART-7.1,SUPERFAMILY-1.75]
12/02/2021 09:59:20:333 Loading file /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
12/02/2021 09:59:20:337 Running the following analyses:
[CDD-3.16,Gene3D-4.2.0,Pfam-32.0,PRINTS-42.0,ProSiteProfiles-2018_02,SMART-7.1,SUPERFAMILY-1.75]
2021-02-12 10:34:46,677 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 134
Command: python3 bin/nucleotide/parseOrfs.py 12 /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.fasta /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.filtered.fasta
Error output from binary:
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/powerapps/share/centos7/miniconda/miniconda2-4.5.4-MakerMPI/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

2021-02-12 10:34:46,686 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 134
Command: python3 bin/nucleotide/parseOrfs.py 12 /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.fasta /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.filtered.fasta
Error output from binary:
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/powerapps/share/centos7/miniconda/miniconda2-4.5.4-MakerMPI/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2021-02-12 10:34:46,688 [amqEmbeddedWorkerJmsContainer-2] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepRunParseGetOrf
2021-02-12 10:34:46,715 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 3 is being re-run following a failure.
2021-02-12 10:34:46,758 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 134
Command: python3 bin/nucleotide/parseOrfs.py 12 /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.fasta /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.filtered.fasta
Error output from binary:
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/powerapps/share/centos7/miniconda/miniconda2-4.5.4-MakerMPI/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

2021-02-12 10:34:46,760 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 134
Command: python3 bin/nucleotide/parseOrfs.py 12 /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.fasta /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.filtered.fasta
Error output from binary:
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/powerapps/share/centos7/miniconda/miniconda2-4.5.4-MakerMPI/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2021-02-12 10:34:46,761 [amqEmbeddedWorkerJmsContainer-3] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepRunParseGetOrf
2021-02-12 10:34:46,839 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:143] WARN - StepInstance 3 is being re-run following a failure.
2021-02-12 10:34:47,080 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 134
Command: python3 bin/nucleotide/parseOrfs.py 12 /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.fasta /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.filtered.fasta
Error output from binary:
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/powerapps/share/centos7/miniconda/miniconda2-4.5.4-MakerMPI/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

2021-02-12 10:34:47,081 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:204] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activity rolled back.
java.lang.IllegalStateException: Command line failed with exit code: 134
Command: python3 bin/nucleotide/parseOrfs.py 12 /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.fasta /groups/itay_mayrose/liorglic/NLRtracker/temp/compute-0-8.power_20210212_095706479_eip2//jobLoadNucleicAcidSequence/orfs.filtered.fasta
Error output from binary:
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/powerapps/share/centos7/miniconda/miniconda2-4.5.4-MakerMPI/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

        at uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep.execute(RunBinaryStep.java:190)
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy106.executeInTransaction(Unknown Source)
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:192)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
        at java.lang.Thread.run(Thread.java:745)
2021-02-12 10:34:47,082 [amqEmbeddedWorkerJmsContainer-8] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:206] ERROR - StepExecution with errors - stepName: stepRunParseGetOrf
2021-02-12 10:34:47,164 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:24] FATAL - Analysis step 3 : Run GetOrf to predict open reading frames from nucleic acid sequence for proteins null to null has failed irretrievably.  Available StackTraces follow.
2021-02-12 10:34:47,165 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:41] FATAL - The JVM will now exit with a non-zero exit status.
2021-02-12 10:34:47,166 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:258] ERROR - Exception thrown by StandaloneBlackBoxMaster:
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:42)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:134)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:377)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

Run FIMO

fimo -o /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/output/NLRtracker/RESULT/fimo_out module/meme.xml /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa
NLRtracker.sh: line 128: fimo: command not found

Interproscan output or FIMO output don't exist.
```

**Comment by slt666666** [comment]
Hi, I guess your error caused by interproscan.
When you run
`interproscan.sh -i /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/data/Hordeum_vulgare.IBSC_v2.dna.toplevel.fa -f gff3 -t n -o /groups/itay_mayrose_nosnap/liorglic/Projects/Barley/output/NLRtracker/RESULT/interpro_result.gff -cpu 60 -appl Pfam,Gene3D,SUPERFAMILY,PRINTS,SMART,CDD,ProSiteProfiles`
and get same error message, your interproscan environment may have a problem.

It looks similar error as below, (it may be caused by Python version...?)
https://www.biostars.org/p/274854/
https://www.biostars.org/p/288036/
Could you please check these points.

**Comment by soungalo** [comment]
Indeed PATH issue. The problem was fixed once I got the server to run python3.
